# Хочу заменить на него

bind_addr: ":8084"
log_level: "debug"
database_url: "host=localhost dbname=apiCargoRest sslmode=disable"
session_key: "dskadbsabdkabkdbakdbkasbdkja"

mail:
  host: "localhost"
  port: 5672
  username: guest
  password: guest
  send_queue: mail