bind_addr: ":8084"
log_level: "debug"
database_url: "host=localhost dbname=apiCargoRest sslmode=disable"
session_key: "dskadbsabdkabkdbakdbkasbdkja"
base_path: "/api/v1"

mail:
  host: "localhost"
  port: 5672
  username: guest
  password: guest
  send_queue: mail

db:
  host: "localhost"
  user: "rasha"
  pass: ""
  dbName: "apiCargoRest"
  maxConnections: 100